### ISSUE TITLE
win binary pls?

### ISSUE THREAD

**Issue by necros2k7** [DrMcCoy/scummvm#2]

**Comment by DrMcCoy** [comment]
I'm sorry, but no, not going to happen.

The current state of this engine is far from ready for players. It needs developers instead. Developers who preferably are able to build their own binaries. :P

Besides, this is currently still based on an older checkout of ScummVM (and adapting it to the current development branch of ScummVM will be some work), and as such is still using SDL 1.2. I don't have SDL 1.2 set up in my cross-compiling mingw at the moment, only SDL 2.

So providing Windows binaries would be more work than I'm willing to put into it, especially since the gain is rather questionable.
